#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AssinaGravaPDF.Resource", IsApplication=true)]

namespace AssinaGravaPDF
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::iTextSharpLGPLMonoForAndroid.Resource.String.library_name = global::AssinaGravaPDF.Resource.String.library_name;
			global::XamiTextSharpLGPL.Droid.Resource.String.library_name = global::AssinaGravaPDF.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050020
			public const int air_force_blue = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int algae_green = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int alice_blue = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int alien_green = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int almond = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int amber = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int american_rose = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int amethyst = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int android_green = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int anti_flash_white = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int antique_brass = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int antique_fuchsia = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int antique_white = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int apple_green = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int apricot = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int aqua = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int aqua_marine = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int army_brown = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int army_green = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int ash_grey = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int asparagus = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int atomic_tangerine = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int aureolin = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int aurometalsaurus = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int avocado_green = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int awesome = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int aztech_purple = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int azure = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int azure_mist_web = 2131034172;
			
			// aapt resource value: 0x7f05003f
			public const int baby_blue = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int baby_blue_eyes = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int baby_pink = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int ball_blue = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int banana_mania = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int banana_yellow = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int bashful_pink = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int basket_ball_orange = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int battleship_grey = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int bazaar = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int bean_red = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int beaver = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int bee_yellow = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int beer = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int beetle_green = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int beige = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int bisque = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int bistre = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int bittersweet = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int black = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int black_cat = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int black_cow = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int black_eel = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int blanched_almond = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int blanchedalmond = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int bleu_de_france = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int blizzard_blue = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int blond = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int blood_red = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int blossom_pink = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int blue = 2131034205;
			
			// aapt resource value: 0x7f05005e
			public const int blue_angel = 2131034206;
			
			// aapt resource value: 0x7f05005f
			public const int blue_bell = 2131034207;
			
			// aapt resource value: 0x7f050060
			public const int blue_diamond = 2131034208;
			
			// aapt resource value: 0x7f050061
			public const int blue_dress = 2131034209;
			
			// aapt resource value: 0x7f050062
			public const int blue_eyes = 2131034210;
			
			// aapt resource value: 0x7f05003d
			public const int blue_fundo = 2131034173;
			
			// aapt resource value: 0x7f050063
			public const int blue_gray = 2131034211;
			
			// aapt resource value: 0x7f050064
			public const int blue_green = 2131034212;
			
			// aapt resource value: 0x7f050065
			public const int blue_hosta = 2131034213;
			
			// aapt resource value: 0x7f050066
			public const int blue_ivy = 2131034214;
			
			// aapt resource value: 0x7f050067
			public const int blue_jay = 2131034215;
			
			// aapt resource value: 0x7f050068
			public const int blue_koi = 2131034216;
			
			// aapt resource value: 0x7f050069
			public const int blue_lagoon = 2131034217;
			
			// aapt resource value: 0x7f05006a
			public const int blue_lotus = 2131034218;
			
			// aapt resource value: 0x7f05006b
			public const int blue_orchid = 2131034219;
			
			// aapt resource value: 0x7f05006c
			public const int blue_purple = 2131034220;
			
			// aapt resource value: 0x7f05006d
			public const int blue_ribbon = 2131034221;
			
			// aapt resource value: 0x7f05003e
			public const int blue_sub_menu = 2131034174;
			
			// aapt resource value: 0x7f05006e
			public const int blue_whale = 2131034222;
			
			// aapt resource value: 0x7f05006f
			public const int blue_zircon = 2131034223;
			
			// aapt resource value: 0x7f050070
			public const int blueberry_blue = 2131034224;
			
			// aapt resource value: 0x7f050071
			public const int blush = 2131034225;
			
			// aapt resource value: 0x7f050072
			public const int blush_pink = 2131034226;
			
			// aapt resource value: 0x7f050073
			public const int blush_red = 2131034227;
			
			// aapt resource value: 0x7f050074
			public const int bole = 2131034228;
			
			// aapt resource value: 0x7f050075
			public const int bondi_blue = 2131034229;
			
			// aapt resource value: 0x7f050076
			public const int bone = 2131034230;
			
			// aapt resource value: 0x7f050077
			public const int bottle_green = 2131034231;
			
			// aapt resource value: 0x7f050078
			public const int boysenberry = 2131034232;
			
			// aapt resource value: 0x7f050079
			public const int brandeis_blue = 2131034233;
			
			// aapt resource value: 0x7f05007a
			public const int brass = 2131034234;
			
			// aapt resource value: 0x7f05007b
			public const int brick_red = 2131034235;
			
			// aapt resource value: 0x7f05007c
			public const int bright_cerulean = 2131034236;
			
			// aapt resource value: 0x7f05007d
			public const int bright_gold = 2131034237;
			
			// aapt resource value: 0x7f05007e
			public const int bright_green = 2131034238;
			
			// aapt resource value: 0x7f05007f
			public const int bright_lavender = 2131034239;
			
			// aapt resource value: 0x7f050080
			public const int bright_maroon = 2131034240;
			
			// aapt resource value: 0x7f050081
			public const int bright_neon_pink = 2131034241;
			
			// aapt resource value: 0x7f050082
			public const int bright_pink = 2131034242;
			
			// aapt resource value: 0x7f050083
			public const int bright_turquoise = 2131034243;
			
			// aapt resource value: 0x7f050084
			public const int bright_ube = 2131034244;
			
			// aapt resource value: 0x7f050085
			public const int brilliant_lavender = 2131034245;
			
			// aapt resource value: 0x7f050086
			public const int brilliant_rose = 2131034246;
			
			// aapt resource value: 0x7f050087
			public const int brink_pink = 2131034247;
			
			// aapt resource value: 0x7f050088
			public const int british_racing_green = 2131034248;
			
			// aapt resource value: 0x7f050089
			public const int bronze = 2131034249;
			
			// aapt resource value: 0x7f05008a
			public const int brown_bear = 2131034250;
			
			// aapt resource value: 0x7f05008b
			public const int brown_sugar = 2131034251;
			
			// aapt resource value: 0x7f05008c
			public const int bubble_gum = 2131034252;
			
			// aapt resource value: 0x7f05008d
			public const int bubbles = 2131034253;
			
			// aapt resource value: 0x7f05008e
			public const int buff = 2131034254;
			
			// aapt resource value: 0x7f05008f
			public const int bulgarian_rose = 2131034255;
			
			// aapt resource value: 0x7f050090
			public const int burgundy = 2131034256;
			
			// aapt resource value: 0x7f050091
			public const int burlywood = 2131034257;
			
			// aapt resource value: 0x7f050092
			public const int burnt_orange = 2131034258;
			
			// aapt resource value: 0x7f050093
			public const int burnt_pink = 2131034259;
			
			// aapt resource value: 0x7f050094
			public const int burnt_sienna = 2131034260;
			
			// aapt resource value: 0x7f050095
			public const int burnt_umber = 2131034261;
			
			// aapt resource value: 0x7f050096
			public const int butterfly_blue = 2131034262;
			
			// aapt resource value: 0x7f050097
			public const int byzantine = 2131034263;
			
			// aapt resource value: 0x7f050098
			public const int byzantium = 2131034264;
			
			// aapt resource value: 0x7f050099
			public const int cadet = 2131034265;
			
			// aapt resource value: 0x7f05009a
			public const int cadet_blue = 2131034266;
			
			// aapt resource value: 0x7f05009b
			public const int cadet_grey = 2131034267;
			
			// aapt resource value: 0x7f05009c
			public const int cadillac_pink = 2131034268;
			
			// aapt resource value: 0x7f05009d
			public const int cadmium_green = 2131034269;
			
			// aapt resource value: 0x7f05009e
			public const int cadmium_orange = 2131034270;
			
			// aapt resource value: 0x7f05009f
			public const int cadmium_red = 2131034271;
			
			// aapt resource value: 0x7f0500a0
			public const int cadmium_yellow = 2131034272;
			
			// aapt resource value: 0x7f0500a1
			public const int cafe_noir = 2131034273;
			
			// aapt resource value: 0x7f0500a2
			public const int cal_poly_pomona_green = 2131034274;
			
			// aapt resource value: 0x7f0500a3
			public const int cambridge_blue = 2131034275;
			
			// aapt resource value: 0x7f0500a4
			public const int camel_brown = 2131034276;
			
			// aapt resource value: 0x7f0500a5
			public const int camouflage_green = 2131034277;
			
			// aapt resource value: 0x7f0500a6
			public const int canary = 2131034278;
			
			// aapt resource value: 0x7f0500a7
			public const int canary_yellow = 2131034279;
			
			// aapt resource value: 0x7f0500a8
			public const int candy_apple_red = 2131034280;
			
			// aapt resource value: 0x7f0500a9
			public const int candy_pink = 2131034281;
			
			// aapt resource value: 0x7f0500aa
			public const int cantaloupe = 2131034282;
			
			// aapt resource value: 0x7f0500ab
			public const int capri = 2131034283;
			
			// aapt resource value: 0x7f0500ac
			public const int caput_mortuum = 2131034284;
			
			// aapt resource value: 0x7f0500ad
			public const int caramel = 2131034285;
			
			// aapt resource value: 0x7f0500ae
			public const int carbon_gray = 2131034286;
			
			// aapt resource value: 0x7f0500af
			public const int cardinal = 2131034287;
			
			// aapt resource value: 0x7f0500b0
			public const int caribbean_green = 2131034288;
			
			// aapt resource value: 0x7f0500b1
			public const int carmine = 2131034289;
			
			// aapt resource value: 0x7f0500b2
			public const int carmine_pink = 2131034290;
			
			// aapt resource value: 0x7f0500b3
			public const int carmine_red = 2131034291;
			
			// aapt resource value: 0x7f0500b4
			public const int carnation_pink_one = 2131034292;
			
			// aapt resource value: 0x7f0500b5
			public const int carnation_pink_three = 2131034293;
			
			// aapt resource value: 0x7f0500b6
			public const int carnation_pink_two = 2131034294;
			
			// aapt resource value: 0x7f0500b7
			public const int carolina_blue = 2131034295;
			
			// aapt resource value: 0x7f0500b8
			public const int carrot_orange = 2131034296;
			
			// aapt resource value: 0x7f0500b9
			public const int celadon = 2131034297;
			
			// aapt resource value: 0x7f0500ba
			public const int celeste = 2131034298;
			
			// aapt resource value: 0x7f0500bb
			public const int celestial_blue = 2131034299;
			
			// aapt resource value: 0x7f0500bc
			public const int cerise_pink = 2131034300;
			
			// aapt resource value: 0x7f0500bd
			public const int cerulean = 2131034301;
			
			// aapt resource value: 0x7f0500be
			public const int cerulean_blue = 2131034302;
			
			// aapt resource value: 0x7f0500bf
			public const int cg_blue = 2131034303;
			
			// aapt resource value: 0x7f0500c0
			public const int cg_red = 2131034304;
			
			// aapt resource value: 0x7f0500c1
			public const int chamoisee = 2131034305;
			
			// aapt resource value: 0x7f0500c2
			public const int champagne = 2131034306;
			
			// aapt resource value: 0x7f0500c3
			public const int charcoal = 2131034307;
			
			// aapt resource value: 0x7f0500c4
			public const int chartreuse = 2131034308;
			
			// aapt resource value: 0x7f0500c5
			public const int cherry = 2131034309;
			
			// aapt resource value: 0x7f0500c6
			public const int cherry_blossom_pink = 2131034310;
			
			// aapt resource value: 0x7f0500c7
			public const int cherry_red = 2131034311;
			
			// aapt resource value: 0x7f0500c8
			public const int chestnut = 2131034312;
			
			// aapt resource value: 0x7f0500c9
			public const int chestnut_red = 2131034313;
			
			// aapt resource value: 0x7f0500ca
			public const int chilli_pepper = 2131034314;
			
			// aapt resource value: 0x7f0500cb
			public const int chocolate = 2131034315;
			
			// aapt resource value: 0x7f0500cc
			public const int chrome_yellow = 2131034316;
			
			// aapt resource value: 0x7f0500cd
			public const int cinereous = 2131034317;
			
			// aapt resource value: 0x7f0500ce
			public const int cinnabar = 2131034318;
			
			// aapt resource value: 0x7f0500cf
			public const int citrine = 2131034319;
			
			// aapt resource value: 0x7f0500d0
			public const int classic_rose = 2131034320;
			
			// aapt resource value: 0x7f0500d1
			public const int cloudy_gray = 2131034321;
			
			// aapt resource value: 0x7f0500d2
			public const int clover_green = 2131034322;
			
			// aapt resource value: 0x7f0500d3
			public const int cobalt = 2131034323;
			
			// aapt resource value: 0x7f0500d4
			public const int cobalt_blue = 2131034324;
			
			// aapt resource value: 0x7f0500d5
			public const int coffee = 2131034325;
			
			// aapt resource value: 0x7f0500d6
			public const int columbia_blue = 2131034326;
			
			// aapt resource value: 0x7f0500d7
			public const int construction_cone_orange = 2131034327;
			
			// aapt resource value: 0x7f0500d8
			public const int cookie_brown = 2131034328;
			
			// aapt resource value: 0x7f0500d9
			public const int cool_black = 2131034329;
			
			// aapt resource value: 0x7f0500da
			public const int cool_grey = 2131034330;
			
			// aapt resource value: 0x7f0500db
			public const int copper = 2131034331;
			
			// aapt resource value: 0x7f0500dc
			public const int copper_rose = 2131034332;
			
			// aapt resource value: 0x7f0500dd
			public const int coquelicot = 2131034333;
			
			// aapt resource value: 0x7f0500de
			public const int coral = 2131034334;
			
			// aapt resource value: 0x7f0500df
			public const int coral_blue = 2131034335;
			
			// aapt resource value: 0x7f0500e0
			public const int coral_pink = 2131034336;
			
			// aapt resource value: 0x7f0500e1
			public const int coral_red = 2131034337;
			
			// aapt resource value: 0x7f0500e2
			public const int cordovan = 2131034338;
			
			// aapt resource value: 0x7f0500e3
			public const int corn = 2131034339;
			
			// aapt resource value: 0x7f0500e4
			public const int corn_yellow = 2131034340;
			
			// aapt resource value: 0x7f0500e5
			public const int cornell_red = 2131034341;
			
			// aapt resource value: 0x7f0500e6
			public const int cornflower = 2131034342;
			
			// aapt resource value: 0x7f0500e7
			public const int cornflower_blue = 2131034343;
			
			// aapt resource value: 0x7f0500e8
			public const int cornsilk = 2131034344;
			
			// aapt resource value: 0x7f0500e9
			public const int cosmic_latte = 2131034345;
			
			// aapt resource value: 0x7f0500ea
			public const int cotton_candy = 2131034346;
			
			// aapt resource value: 0x7f0500eb
			public const int cranberry = 2131034347;
			
			// aapt resource value: 0x7f0500ec
			public const int cream = 2131034348;
			
			// aapt resource value: 0x7f0500ed
			public const int crimson = 2131034349;
			
			// aapt resource value: 0x7f0500ee
			public const int crimson_glory = 2131034350;
			
			// aapt resource value: 0x7f0500ef
			public const int crimson_red = 2131034351;
			
			// aapt resource value: 0x7f0500f0
			public const int crocus_purple = 2131034352;
			
			// aapt resource value: 0x7f0500f1
			public const int crystal_blue = 2131034353;
			
			// aapt resource value: 0x7f0500f2
			public const int cyan = 2131034354;
			
			// aapt resource value: 0x7f0500f3
			public const int cyan_opaque = 2131034355;
			
			// aapt resource value: 0x7f0500f4
			public const int daffodil = 2131034356;
			
			// aapt resource value: 0x7f0500f5
			public const int dandelion = 2131034357;
			
			// aapt resource value: 0x7f0500f6
			public const int dark_blue = 2131034358;
			
			// aapt resource value: 0x7f0500f7
			public const int dark_brown = 2131034359;
			
			// aapt resource value: 0x7f0500f8
			public const int dark_byzantium = 2131034360;
			
			// aapt resource value: 0x7f0500f9
			public const int dark_candy_apple_red = 2131034361;
			
			// aapt resource value: 0x7f0500fa
			public const int dark_cerulean = 2131034362;
			
			// aapt resource value: 0x7f0500fb
			public const int dark_chestnut = 2131034363;
			
			// aapt resource value: 0x7f0500fc
			public const int dark_coral = 2131034364;
			
			// aapt resource value: 0x7f0500fd
			public const int dark_cyan = 2131034365;
			
			// aapt resource value: 0x7f0500fe
			public const int dark_electric_blue = 2131034366;
			
			// aapt resource value: 0x7f0500ff
			public const int dark_forrest_green = 2131034367;
			
			// aapt resource value: 0x7f050100
			public const int dark_goldenrod = 2131034368;
			
			// aapt resource value: 0x7f050101
			public const int dark_gray = 2131034369;
			
			// aapt resource value: 0x7f050102
			public const int dark_green = 2131034370;
			
			// aapt resource value: 0x7f050103
			public const int dark_jungle_green = 2131034371;
			
			// aapt resource value: 0x7f050104
			public const int dark_khaki = 2131034372;
			
			// aapt resource value: 0x7f050105
			public const int dark_lavender = 2131034373;
			
			// aapt resource value: 0x7f050106
			public const int dark_magenta = 2131034374;
			
			// aapt resource value: 0x7f050107
			public const int dark_midnight_blue = 2131034375;
			
			// aapt resource value: 0x7f050108
			public const int dark_olive_green = 2131034376;
			
			// aapt resource value: 0x7f050109
			public const int dark_orange = 2131034377;
			
			// aapt resource value: 0x7f05010a
			public const int dark_orchid = 2131034378;
			
			// aapt resource value: 0x7f05010b
			public const int dark_pastel_blue = 2131034379;
			
			// aapt resource value: 0x7f05010c
			public const int dark_pastel_green = 2131034380;
			
			// aapt resource value: 0x7f05010d
			public const int dark_pastel_purple = 2131034381;
			
			// aapt resource value: 0x7f05010e
			public const int dark_pastel_red = 2131034382;
			
			// aapt resource value: 0x7f05010f
			public const int dark_pink = 2131034383;
			
			// aapt resource value: 0x7f050110
			public const int dark_powder_blue = 2131034384;
			
			// aapt resource value: 0x7f050111
			public const int dark_raspberry = 2131034385;
			
			// aapt resource value: 0x7f050112
			public const int dark_red = 2131034386;
			
			// aapt resource value: 0x7f050113
			public const int dark_salmon = 2131034387;
			
			// aapt resource value: 0x7f050114
			public const int dark_scarlet = 2131034388;
			
			// aapt resource value: 0x7f050115
			public const int dark_sea_green = 2131034389;
			
			// aapt resource value: 0x7f050116
			public const int dark_sienna = 2131034390;
			
			// aapt resource value: 0x7f050117
			public const int dark_slate_blue = 2131034391;
			
			// aapt resource value: 0x7f050118
			public const int dark_slate_gray = 2131034392;
			
			// aapt resource value: 0x7f050119
			public const int dark_spring_green = 2131034393;
			
			// aapt resource value: 0x7f05011a
			public const int dark_tan = 2131034394;
			
			// aapt resource value: 0x7f05011b
			public const int dark_tangerine = 2131034395;
			
			// aapt resource value: 0x7f05011c
			public const int dark_terra_cotta = 2131034396;
			
			// aapt resource value: 0x7f05011d
			public const int dark_turquoise = 2131034397;
			
			// aapt resource value: 0x7f05011e
			public const int dark_violet = 2131034398;
			
			// aapt resource value: 0x7f05011f
			public const int dartmouth_green = 2131034399;
			
			// aapt resource value: 0x7f050120
			public const int davy_grey = 2131034400;
			
			// aapt resource value: 0x7f050121
			public const int debian_red = 2131034401;
			
			// aapt resource value: 0x7f050122
			public const int deep_carmine = 2131034402;
			
			// aapt resource value: 0x7f050123
			public const int deep_carmine_pink = 2131034403;
			
			// aapt resource value: 0x7f050124
			public const int deep_carrot_orange = 2131034404;
			
			// aapt resource value: 0x7f050125
			public const int deep_cerise = 2131034405;
			
			// aapt resource value: 0x7f050126
			public const int deep_champagne = 2131034406;
			
			// aapt resource value: 0x7f050127
			public const int deep_chestnut = 2131034407;
			
			// aapt resource value: 0x7f050128
			public const int deep_coffee = 2131034408;
			
			// aapt resource value: 0x7f050129
			public const int deep_fuchsia = 2131034409;
			
			// aapt resource value: 0x7f05012a
			public const int deep_jungle_green = 2131034410;
			
			// aapt resource value: 0x7f05012b
			public const int deep_lilac = 2131034411;
			
			// aapt resource value: 0x7f05012c
			public const int deep_magenta = 2131034412;
			
			// aapt resource value: 0x7f05012d
			public const int deep_peach = 2131034413;
			
			// aapt resource value: 0x7f05012e
			public const int deep_pink = 2131034414;
			
			// aapt resource value: 0x7f05012f
			public const int deep_saffron = 2131034415;
			
			// aapt resource value: 0x7f050130
			public const int deep_sky_blue = 2131034416;
			
			// aapt resource value: 0x7f050131
			public const int denim = 2131034417;
			
			// aapt resource value: 0x7f050132
			public const int denim_blue = 2131034418;
			
			// aapt resource value: 0x7f050133
			public const int desert_sand = 2131034419;
			
			// aapt resource value: 0x7f050134
			public const int dim_gray = 2131034420;
			
			// aapt resource value: 0x7f050135
			public const int dimorphotheca_magenta = 2131034421;
			
			// aapt resource value: 0x7f05001c
			public const int disabled_and_focused_border = 2131034140;
			
			// aapt resource value: 0x7f05001b
			public const int disabled_and_focused_end = 2131034139;
			
			// aapt resource value: 0x7f05001f
			public const int disabled_and_focused_end_multi = 2131034143;
			
			// aapt resource value: 0x7f05001a
			public const int disabled_and_focused_start = 2131034138;
			
			// aapt resource value: 0x7f05001e
			public const int disabled_and_focused_start_multi = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int disabled_and_focused_text = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int disabled_border = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int disabled_end = 2131034133;
			
			// aapt resource value: 0x7f050019
			public const int disabled_end_multi = 2131034137;
			
			// aapt resource value: 0x7f050014
			public const int disabled_start = 2131034132;
			
			// aapt resource value: 0x7f050018
			public const int disabled_start_multi = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int disabled_text = 2131034135;
			
			// aapt resource value: 0x7f050136
			public const int dodger_blue = 2131034422;
			
			// aapt resource value: 0x7f050137
			public const int dogwood_rose = 2131034423;
			
			// aapt resource value: 0x7f050138
			public const int dollar_bill_green = 2131034424;
			
			// aapt resource value: 0x7f050139
			public const int dragon_green = 2131034425;
			
			// aapt resource value: 0x7f05013a
			public const int duke_blue = 2131034426;
			
			// aapt resource value: 0x7f05013b
			public const int dull_purple = 2131034427;
			
			// aapt resource value: 0x7f05013c
			public const int earth_blue = 2131034428;
			
			// aapt resource value: 0x7f05013d
			public const int earth_yellow = 2131034429;
			
			// aapt resource value: 0x7f05013e
			public const int eggplant = 2131034430;
			
			// aapt resource value: 0x7f05013f
			public const int eggshell = 2131034431;
			
			// aapt resource value: 0x7f050140
			public const int egyptian_blue = 2131034432;
			
			// aapt resource value: 0x7f050141
			public const int electric_blue = 2131034433;
			
			// aapt resource value: 0x7f050142
			public const int electric_crimson = 2131034434;
			
			// aapt resource value: 0x7f050143
			public const int electric_green = 2131034435;
			
			// aapt resource value: 0x7f050144
			public const int electric_indigo = 2131034436;
			
			// aapt resource value: 0x7f050145
			public const int electric_lavender = 2131034437;
			
			// aapt resource value: 0x7f050146
			public const int electric_purple = 2131034438;
			
			// aapt resource value: 0x7f050147
			public const int electric_ultramarine = 2131034439;
			
			// aapt resource value: 0x7f050148
			public const int electric_violet = 2131034440;
			
			// aapt resource value: 0x7f050149
			public const int emerald = 2131034441;
			
			// aapt resource value: 0x7f05014a
			public const int emerald_green = 2131034442;
			
			// aapt resource value: 0x7f05014b
			public const int eton_blue = 2131034443;
			
			// aapt resource value: 0x7f05014c
			public const int fall_leaf_brown = 2131034444;
			
			// aapt resource value: 0x7f05014d
			public const int falu_red = 2131034445;
			
			// aapt resource value: 0x7f05014e
			public const int famous = 2131034446;
			
			// aapt resource value: 0x7f05014f
			public const int fandango = 2131034447;
			
			// aapt resource value: 0x7f050150
			public const int fashion_fuchsia = 2131034448;
			
			// aapt resource value: 0x7f050151
			public const int fawn = 2131034449;
			
			// aapt resource value: 0x7f050152
			public const int feldgrau = 2131034450;
			
			// aapt resource value: 0x7f050153
			public const int fern = 2131034451;
			
			// aapt resource value: 0x7f050154
			public const int fern_green = 2131034452;
			
			// aapt resource value: 0x7f050155
			public const int ferrari_red = 2131034453;
			
			// aapt resource value: 0x7f050156
			public const int field_drab = 2131034454;
			
			// aapt resource value: 0x7f050157
			public const int fire_engine_red = 2131034455;
			
			// aapt resource value: 0x7f050158
			public const int firebrick = 2131034456;
			
			// aapt resource value: 0x7f050159
			public const int flame = 2131034457;
			
			// aapt resource value: 0x7f05015a
			public const int flamingo_pink = 2131034458;
			
			// aapt resource value: 0x7f05015b
			public const int flavescent = 2131034459;
			
			// aapt resource value: 0x7f05015c
			public const int flax = 2131034460;
			
			// aapt resource value: 0x7f05015d
			public const int floral_white = 2131034461;
			
			// aapt resource value: 0x7f05015e
			public const int fluorescent_pink = 2131034462;
			
			// aapt resource value: 0x7f05015f
			public const int fluorescent_yellow = 2131034463;
			
			// aapt resource value: 0x7f05000e
			public const int focused_border = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int focused_end = 2131034125;
			
			// aapt resource value: 0x7f050011
			public const int focused_end_multi = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int focused_end_multi_1 = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int focused_start = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int focused_start_multi = 2131034128;
			
			// aapt resource value: 0x7f050012
			public const int focused_start_multi_1 = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int focused_text = 2131034127;
			
			// aapt resource value: 0x7f050160
			public const int folly = 2131034464;
			
			// aapt resource value: 0x7f050161
			public const int forest_green = 2131034465;
			
			// aapt resource value: 0x7f050162
			public const int french_beige = 2131034466;
			
			// aapt resource value: 0x7f050163
			public const int french_blue = 2131034467;
			
			// aapt resource value: 0x7f050164
			public const int french_lilac = 2131034468;
			
			// aapt resource value: 0x7f050165
			public const int french_rose = 2131034469;
			
			// aapt resource value: 0x7f050166
			public const int frog_green = 2131034470;
			
			// aapt resource value: 0x7f050167
			public const int fuchsia = 2131034471;
			
			// aapt resource value: 0x7f050168
			public const int fuchsia_pink = 2131034472;
			
			// aapt resource value: 0x7f050169
			public const int fulvous = 2131034473;
			
			// aapt resource value: 0x7f05016a
			public const int fuzzy_wuzzy = 2131034474;
			
			// aapt resource value: 0x7f05016b
			public const int gainsboro = 2131034475;
			
			// aapt resource value: 0x7f05016c
			public const int gamboge = 2131034476;
			
			// aapt resource value: 0x7f05016d
			public const int ghost_white = 2131034477;
			
			// aapt resource value: 0x7f05016e
			public const int ginger = 2131034478;
			
			// aapt resource value: 0x7f05016f
			public const int ginger_brown = 2131034479;
			
			// aapt resource value: 0x7f050170
			public const int glaucous = 2131034480;
			
			// aapt resource value: 0x7f050171
			public const int glitter = 2131034481;
			
			// aapt resource value: 0x7f050172
			public const int gold = 2131034482;
			
			// aapt resource value: 0x7f050173
			public const int golden = 2131034483;
			
			// aapt resource value: 0x7f050174
			public const int golden_brown = 2131034484;
			
			// aapt resource value: 0x7f050175
			public const int golden_poppy = 2131034485;
			
			// aapt resource value: 0x7f050176
			public const int golden_yellow = 2131034486;
			
			// aapt resource value: 0x7f050177
			public const int goldenrod = 2131034487;
			
			// aapt resource value: 0x7f050178
			public const int granite = 2131034488;
			
			// aapt resource value: 0x7f050179
			public const int granny_smith_apple = 2131034489;
			
			// aapt resource value: 0x7f05017a
			public const int grape = 2131034490;
			
			// aapt resource value: 0x7f05017b
			public const int grapefruit = 2131034491;
			
			// aapt resource value: 0x7f05017c
			public const int gray_asparagus = 2131034492;
			
			// aapt resource value: 0x7f05017d
			public const int gray_cloud = 2131034493;
			
			// aapt resource value: 0x7f05017e
			public const int gray_dolphin = 2131034494;
			
			// aapt resource value: 0x7f05017f
			public const int gray_goose = 2131034495;
			
			// aapt resource value: 0x7f050180
			public const int gray_wolf = 2131034496;
			
			// aapt resource value: 0x7f050181
			public const int grayish_turquoise = 2131034497;
			
			// aapt resource value: 0x7f050182
			public const int green_apple = 2131034498;
			
			// aapt resource value: 0x7f050183
			public const int green_blue = 2131034499;
			
			// aapt resource value: 0x7f050184
			public const int green_onion = 2131034500;
			
			// aapt resource value: 0x7f050185
			public const int green_peas = 2131034501;
			
			// aapt resource value: 0x7f050186
			public const int green_snake = 2131034502;
			
			// aapt resource value: 0x7f050187
			public const int green_thumb = 2131034503;
			
			// aapt resource value: 0x7f050188
			public const int green_yellow = 2131034504;
			
			// aapt resource value: 0x7f050189
			public const int greenish_blue = 2131034505;
			
			// aapt resource value: 0x7f05018a
			public const int grey = 2131034506;
			
			// aapt resource value: 0x7f05018b
			public const int grullo = 2131034507;
			
			// aapt resource value: 0x7f05018c
			public const int gunmetal = 2131034508;
			
			// aapt resource value: 0x7f05018d
			public const int guppie_green = 2131034509;
			
			// aapt resource value: 0x7f05018e
			public const int halaya_ube = 2131034510;
			
			// aapt resource value: 0x7f05018f
			public const int halloween_orange = 2131034511;
			
			// aapt resource value: 0x7f050190
			public const int han_blue = 2131034512;
			
			// aapt resource value: 0x7f050191
			public const int han_purple = 2131034513;
			
			// aapt resource value: 0x7f050192
			public const int hansa_yellow = 2131034514;
			
			// aapt resource value: 0x7f050193
			public const int harlequin = 2131034515;
			
			// aapt resource value: 0x7f050194
			public const int harvard_crimson = 2131034516;
			
			// aapt resource value: 0x7f050195
			public const int harvest_gold = 2131034517;
			
			// aapt resource value: 0x7f050196
			public const int hazel_green = 2131034518;
			
			// aapt resource value: 0x7f050197
			public const int heliotrope = 2131034519;
			
			// aapt resource value: 0x7f050198
			public const int heliotrope_purple = 2131034520;
			
			// aapt resource value: 0x7f050199
			public const int hollywood_cerise = 2131034521;
			
			// aapt resource value: 0x7f05019a
			public const int honeydew = 2131034522;
			
			// aapt resource value: 0x7f05019b
			public const int hooker_green = 2131034523;
			
			// aapt resource value: 0x7f05019c
			public const int hot_magenta = 2131034524;
			
			// aapt resource value: 0x7f05019d
			public const int hot_pink = 2131034525;
			
			// aapt resource value: 0x7f05019e
			public const int hummingbird_green = 2131034526;
			
			// aapt resource value: 0x7f05019f
			public const int hunter_green = 2131034527;
			
			// aapt resource value: 0x7f0501a0
			public const int iceberg = 2131034528;
			
			// aapt resource value: 0x7f0501a1
			public const int icterine = 2131034529;
			
			// aapt resource value: 0x7f0501a2
			public const int iguana_green = 2131034530;
			
			// aapt resource value: 0x7f0501a3
			public const int inchworm = 2131034531;
			
			// aapt resource value: 0x7f0501a4
			public const int india_green = 2131034532;
			
			// aapt resource value: 0x7f0501a5
			public const int indian_yellow = 2131034533;
			
			// aapt resource value: 0x7f0501a6
			public const int indigo = 2131034534;
			
			// aapt resource value: 0x7f0501a7
			public const int international_klein_blue = 2131034535;
			
			// aapt resource value: 0x7f0501a8
			public const int international_orange = 2131034536;
			
			// aapt resource value: 0x7f0501a9
			public const int iris = 2131034537;
			
			// aapt resource value: 0x7f0501aa
			public const int isabelline = 2131034538;
			
			// aapt resource value: 0x7f0501ab
			public const int islamic_green = 2131034539;
			
			// aapt resource value: 0x7f0501ac
			public const int ivory = 2131034540;
			
			// aapt resource value: 0x7f0501ad
			public const int jade = 2131034541;
			
			// aapt resource value: 0x7f0501ae
			public const int jasmine = 2131034542;
			
			// aapt resource value: 0x7f0501af
			public const int jasmine_purple = 2131034543;
			
			// aapt resource value: 0x7f0501b0
			public const int jasper = 2131034544;
			
			// aapt resource value: 0x7f0501b1
			public const int jazzberry_jam = 2131034545;
			
			// aapt resource value: 0x7f0501b2
			public const int jeans_blue = 2131034546;
			
			// aapt resource value: 0x7f0501b3
			public const int jellyfish = 2131034547;
			
			// aapt resource value: 0x7f0501b4
			public const int jet_gray = 2131034548;
			
			// aapt resource value: 0x7f0501b5
			public const int jonquil = 2131034549;
			
			// aapt resource value: 0x7f0501b6
			public const int june_bud = 2131034550;
			
			// aapt resource value: 0x7f0501b7
			public const int jungle_green = 2131034551;
			
			// aapt resource value: 0x7f0501b8
			public const int kelly_green = 2131034552;
			
			// aapt resource value: 0x7f0501b9
			public const int khaki = 2131034553;
			
			// aapt resource value: 0x7f0501ba
			public const int khaki_rose = 2131034554;
			
			// aapt resource value: 0x7f0501bb
			public const int ku_crimson = 2131034555;
			
			// aapt resource value: 0x7f0501bc
			public const int la_salle_green = 2131034556;
			
			// aapt resource value: 0x7f0501bd
			public const int languid_lavender = 2131034557;
			
			// aapt resource value: 0x7f0501be
			public const int lapis_blue = 2131034558;
			
			// aapt resource value: 0x7f0501bf
			public const int lapis_lazuli = 2131034559;
			
			// aapt resource value: 0x7f0501c0
			public const int laser_lemon = 2131034560;
			
			// aapt resource value: 0x7f0501c1
			public const int laurel_green = 2131034561;
			
			// aapt resource value: 0x7f0501c2
			public const int lava = 2131034562;
			
			// aapt resource value: 0x7f0501c3
			public const int lava_red = 2131034563;
			
			// aapt resource value: 0x7f0501c4
			public const int lavender = 2131034564;
			
			// aapt resource value: 0x7f0501c5
			public const int lavender_blue = 2131034565;
			
			// aapt resource value: 0x7f0501c6
			public const int lavender_blush = 2131034566;
			
			// aapt resource value: 0x7f0501c7
			public const int lavender_gray = 2131034567;
			
			// aapt resource value: 0x7f0501c8
			public const int lavender_indigo = 2131034568;
			
			// aapt resource value: 0x7f0501c9
			public const int lavender_magenta = 2131034569;
			
			// aapt resource value: 0x7f0501ca
			public const int lavender_pink = 2131034570;
			
			// aapt resource value: 0x7f0501cb
			public const int lavender_pinocchio = 2131034571;
			
			// aapt resource value: 0x7f0501cc
			public const int lavender_purple = 2131034572;
			
			// aapt resource value: 0x7f0501cd
			public const int lavender_rose = 2131034573;
			
			// aapt resource value: 0x7f0501ce
			public const int lawn_green = 2131034574;
			
			// aapt resource value: 0x7f0501cf
			public const int lemon = 2131034575;
			
			// aapt resource value: 0x7f0501d0
			public const int lemon_chiffon = 2131034576;
			
			// aapt resource value: 0x7f0501d1
			public const int lemon_lime = 2131034577;
			
			// aapt resource value: 0x7f0501d2
			public const int lemon_yellow = 2131034578;
			
			// aapt resource value: 0x7f0501d3
			public const int light_apricot = 2131034579;
			
			// aapt resource value: 0x7f0501d4
			public const int light_aquamarine = 2131034580;
			
			// aapt resource value: 0x7f0501d5
			public const int light_blue = 2131034581;
			
			// aapt resource value: 0x7f0501d6
			public const int light_brown = 2131034582;
			
			// aapt resource value: 0x7f0501d7
			public const int light_carmine_pink = 2131034583;
			
			// aapt resource value: 0x7f0501d8
			public const int light_coral = 2131034584;
			
			// aapt resource value: 0x7f0501d9
			public const int light_cornflower_blue = 2131034585;
			
			// aapt resource value: 0x7f0501da
			public const int light_crimson = 2131034586;
			
			// aapt resource value: 0x7f0501db
			public const int light_cyan = 2131034587;
			
			// aapt resource value: 0x7f0501dc
			public const int light_fuchsia_pink = 2131034588;
			
			// aapt resource value: 0x7f0501dd
			public const int light_goldenrod_yellow = 2131034589;
			
			// aapt resource value: 0x7f0501de
			public const int light_gray = 2131034590;
			
			// aapt resource value: 0x7f0501df
			public const int light_green = 2131034591;
			
			// aapt resource value: 0x7f0501e0
			public const int light_jade = 2131034592;
			
			// aapt resource value: 0x7f0501e1
			public const int light_khaki = 2131034593;
			
			// aapt resource value: 0x7f0501e2
			public const int light_pastel_purple = 2131034594;
			
			// aapt resource value: 0x7f0501e3
			public const int light_pink = 2131034595;
			
			// aapt resource value: 0x7f0501e4
			public const int light_salmon = 2131034596;
			
			// aapt resource value: 0x7f0501e5
			public const int light_salmon_pink = 2131034597;
			
			// aapt resource value: 0x7f0501e6
			public const int light_sea_green = 2131034598;
			
			// aapt resource value: 0x7f0501e7
			public const int light_sky_blue = 2131034599;
			
			// aapt resource value: 0x7f0501e8
			public const int light_slate = 2131034600;
			
			// aapt resource value: 0x7f0501e9
			public const int light_slate_blue = 2131034601;
			
			// aapt resource value: 0x7f0501ea
			public const int light_slate_gray = 2131034602;
			
			// aapt resource value: 0x7f0501eb
			public const int light_steel_blue = 2131034603;
			
			// aapt resource value: 0x7f0501ec
			public const int light_taupe = 2131034604;
			
			// aapt resource value: 0x7f0501ed
			public const int light_thulian_pink = 2131034605;
			
			// aapt resource value: 0x7f0501ee
			public const int light_yellow = 2131034606;
			
			// aapt resource value: 0x7f0501ef
			public const int lilac = 2131034607;
			
			// aapt resource value: 0x7f0501f0
			public const int lime_green = 2131034608;
			
			// aapt resource value: 0x7f0501f1
			public const int lincoln_green = 2131034609;
			
			// aapt resource value: 0x7f0501f2
			public const int linen = 2131034610;
			
			// aapt resource value: 0x7f0501f3
			public const int lipstick_pink = 2131034611;
			
			// aapt resource value: 0x7f0501f4
			public const int liver = 2131034612;
			
			// aapt resource value: 0x7f0501f5
			public const int love_red = 2131034613;
			
			// aapt resource value: 0x7f0501f6
			public const int lovely_purple = 2131034614;
			
			// aapt resource value: 0x7f0501f7
			public const int lust = 2131034615;
			
			// aapt resource value: 0x7f0501f8
			public const int macaroni_and_cheese = 2131034616;
			
			// aapt resource value: 0x7f0501f9
			public const int magenta = 2131034617;
			
			// aapt resource value: 0x7f0501fa
			public const int magic_mint = 2131034618;
			
			// aapt resource value: 0x7f0501fb
			public const int magnolia = 2131034619;
			
			// aapt resource value: 0x7f0501fc
			public const int mahogany = 2131034620;
			
			// aapt resource value: 0x7f0501fd
			public const int maize = 2131034621;
			
			// aapt resource value: 0x7f0501fe
			public const int majorelle_blue = 2131034622;
			
			// aapt resource value: 0x7f0501ff
			public const int malachite = 2131034623;
			
			// aapt resource value: 0x7f050200
			public const int manatee = 2131034624;
			
			// aapt resource value: 0x7f050201
			public const int mango_orange = 2131034625;
			
			// aapt resource value: 0x7f050202
			public const int mango_tango = 2131034626;
			
			// aapt resource value: 0x7f050203
			public const int mantis = 2131034627;
			
			// aapt resource value: 0x7f050204
			public const int marble_blue = 2131034628;
			
			// aapt resource value: 0x7f050205
			public const int maroon = 2131034629;
			
			// aapt resource value: 0x7f050206
			public const int mascaw_blue_green = 2131034630;
			
			// aapt resource value: 0x7f050207
			public const int mauve = 2131034631;
			
			// aapt resource value: 0x7f050208
			public const int mauvelous = 2131034632;
			
			// aapt resource value: 0x7f050209
			public const int maya_blue = 2131034633;
			
			// aapt resource value: 0x7f05020a
			public const int meat_brown = 2131034634;
			
			// aapt resource value: 0x7f05020b
			public const int medium_aquamarine = 2131034635;
			
			// aapt resource value: 0x7f05020c
			public const int medium_blue = 2131034636;
			
			// aapt resource value: 0x7f05020d
			public const int medium_candy_apple_red = 2131034637;
			
			// aapt resource value: 0x7f05020e
			public const int medium_champagne = 2131034638;
			
			// aapt resource value: 0x7f05020f
			public const int medium_electric_blue = 2131034639;
			
			// aapt resource value: 0x7f050210
			public const int medium_forest_green = 2131034640;
			
			// aapt resource value: 0x7f050211
			public const int medium_jungle_green = 2131034641;
			
			// aapt resource value: 0x7f050212
			public const int medium_lavender_magenta = 2131034642;
			
			// aapt resource value: 0x7f050213
			public const int medium_orchid = 2131034643;
			
			// aapt resource value: 0x7f050214
			public const int medium_persian_blue = 2131034644;
			
			// aapt resource value: 0x7f050215
			public const int medium_purple = 2131034645;
			
			// aapt resource value: 0x7f050216
			public const int medium_red_violet = 2131034646;
			
			// aapt resource value: 0x7f050217
			public const int medium_sea_green = 2131034647;
			
			// aapt resource value: 0x7f050218
			public const int medium_slate_blue = 2131034648;
			
			// aapt resource value: 0x7f050219
			public const int medium_spring_bud = 2131034649;
			
			// aapt resource value: 0x7f05021a
			public const int medium_spring_green = 2131034650;
			
			// aapt resource value: 0x7f05021b
			public const int medium_taupe = 2131034651;
			
			// aapt resource value: 0x7f05021c
			public const int medium_teal_blue = 2131034652;
			
			// aapt resource value: 0x7f05021d
			public const int medium_turquoise = 2131034653;
			
			// aapt resource value: 0x7f05021e
			public const int medium_violet_red = 2131034654;
			
			// aapt resource value: 0x7f05021f
			public const int melon = 2131034655;
			
			// aapt resource value: 0x7f050220
			public const int metallic_silver = 2131034656;
			
			// aapt resource value: 0x7f050221
			public const int midnight = 2131034657;
			
			// aapt resource value: 0x7f050222
			public const int midnight_blue = 2131034658;
			
			// aapt resource value: 0x7f050223
			public const int midnight_green = 2131034659;
			
			// aapt resource value: 0x7f050224
			public const int mikado_yellow = 2131034660;
			
			// aapt resource value: 0x7f050225
			public const int milk_white = 2131034661;
			
			// aapt resource value: 0x7f050226
			public const int mint = 2131034662;
			
			// aapt resource value: 0x7f050227
			public const int mint_cream = 2131034663;
			
			// aapt resource value: 0x7f050228
			public const int mint_green = 2131034664;
			
			// aapt resource value: 0x7f050229
			public const int mist_blue = 2131034665;
			
			// aapt resource value: 0x7f05022a
			public const int misty_rose = 2131034666;
			
			// aapt resource value: 0x7f05022b
			public const int moccasin = 2131034667;
			
			// aapt resource value: 0x7f05022c
			public const int mocha = 2131034668;
			
			// aapt resource value: 0x7f05022d
			public const int moonstone_blue = 2131034669;
			
			// aapt resource value: 0x7f05022e
			public const int mordant_red_19 = 2131034670;
			
			// aapt resource value: 0x7f05022f
			public const int moss_green = 2131034671;
			
			// aapt resource value: 0x7f050230
			public const int mountain_meadow = 2131034672;
			
			// aapt resource value: 0x7f050231
			public const int mountbatten_pink = 2131034673;
			
			// aapt resource value: 0x7f050232
			public const int msu_green = 2131034674;
			
			// aapt resource value: 0x7f050233
			public const int mulberry = 2131034675;
			
			// aapt resource value: 0x7f050234
			public const int mustard = 2131034676;
			
			// aapt resource value: 0x7f050235
			public const int myrtle = 2131034677;
			
			// aapt resource value: 0x7f050236
			public const int nadeshiko_pink = 2131034678;
			
			// aapt resource value: 0x7f050237
			public const int napier_green = 2131034679;
			
			// aapt resource value: 0x7f050238
			public const int naples_yellow = 2131034680;
			
			// aapt resource value: 0x7f050239
			public const int navajo_white = 2131034681;
			
			// aapt resource value: 0x7f05023a
			public const int navy_blue = 2131034682;
			
			// aapt resource value: 0x7f05023b
			public const int nebula_green = 2131034683;
			
			// aapt resource value: 0x7f05023c
			public const int neon_carrot = 2131034684;
			
			// aapt resource value: 0x7f05023d
			public const int neon_fuchsia = 2131034685;
			
			// aapt resource value: 0x7f05023e
			public const int neon_green = 2131034686;
			
			// aapt resource value: 0x7f05023f
			public const int neon_pink = 2131034687;
			
			// aapt resource value: 0x7f050240
			public const int non_photo_blue = 2131034688;
			
			// aapt resource value: 0x7f050002
			public const int normal_border = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int normal_end = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int normal_end_multi = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int normal_start = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int normal_start_multi = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int normal_text = 2131034115;
			
			// aapt resource value: 0x7f050241
			public const int north_texas_green = 2131034689;
			
			// aapt resource value: 0x7f050242
			public const int northern_lights_blue = 2131034690;
			
			// aapt resource value: 0x7f050243
			public const int oak_brown = 2131034691;
			
			// aapt resource value: 0x7f050244
			public const int ocean_blue = 2131034692;
			
			// aapt resource value: 0x7f050245
			public const int ocean_boat_blue = 2131034693;
			
			// aapt resource value: 0x7f050246
			public const int ochre = 2131034694;
			
			// aapt resource value: 0x7f050247
			public const int office_green = 2131034695;
			
			// aapt resource value: 0x7f050248
			public const int oil = 2131034696;
			
			// aapt resource value: 0x7f050249
			public const int old_gold = 2131034697;
			
			// aapt resource value: 0x7f05024a
			public const int old_lace = 2131034698;
			
			// aapt resource value: 0x7f05024b
			public const int old_lavender = 2131034699;
			
			// aapt resource value: 0x7f05024c
			public const int old_mauve = 2131034700;
			
			// aapt resource value: 0x7f05024d
			public const int old_rose = 2131034701;
			
			// aapt resource value: 0x7f05024e
			public const int olive = 2131034702;
			
			// aapt resource value: 0x7f05024f
			public const int olive_drab = 2131034703;
			
			// aapt resource value: 0x7f050250
			public const int olive_green = 2131034704;
			
			// aapt resource value: 0x7f050251
			public const int olivine = 2131034705;
			
			// aapt resource value: 0x7f050252
			public const int onyx = 2131034706;
			
			// aapt resource value: 0x7f050253
			public const int opera_mauve = 2131034707;
			
			// aapt resource value: 0x7f050254
			public const int orange = 2131034708;
			
			// aapt resource value: 0x7f050255
			public const int orange_peel = 2131034709;
			
			// aapt resource value: 0x7f050256
			public const int orange_red = 2131034710;
			
			// aapt resource value: 0x7f050257
			public const int orange_salmon = 2131034711;
			
			// aapt resource value: 0x7f050258
			public const int orange_yellow = 2131034712;
			
			// aapt resource value: 0x7f050259
			public const int orchid = 2131034713;
			
			// aapt resource value: 0x7f05025a
			public const int outer_space = 2131034714;
			
			// aapt resource value: 0x7f05025b
			public const int outrageous_orange = 2131034715;
			
			// aapt resource value: 0x7f05025c
			public const int oxford_blue = 2131034716;
			
			// aapt resource value: 0x7f05025d
			public const int pacific_blue = 2131034717;
			
			// aapt resource value: 0x7f05025e
			public const int pakistan_green = 2131034718;
			
			// aapt resource value: 0x7f05025f
			public const int palatinate_blue = 2131034719;
			
			// aapt resource value: 0x7f050260
			public const int palatinate_purple = 2131034720;
			
			// aapt resource value: 0x7f050261
			public const int pale_aqua = 2131034721;
			
			// aapt resource value: 0x7f050262
			public const int pale_blue = 2131034722;
			
			// aapt resource value: 0x7f050263
			public const int pale_blue_lily = 2131034723;
			
			// aapt resource value: 0x7f050264
			public const int pale_brown = 2131034724;
			
			// aapt resource value: 0x7f050265
			public const int pale_carmine = 2131034725;
			
			// aapt resource value: 0x7f050266
			public const int pale_cerulean = 2131034726;
			
			// aapt resource value: 0x7f050267
			public const int pale_chestnut = 2131034727;
			
			// aapt resource value: 0x7f050268
			public const int pale_copper = 2131034728;
			
			// aapt resource value: 0x7f050269
			public const int pale_cornflower_blue = 2131034729;
			
			// aapt resource value: 0x7f05026a
			public const int pale_gold = 2131034730;
			
			// aapt resource value: 0x7f05026b
			public const int pale_goldenrod = 2131034731;
			
			// aapt resource value: 0x7f05026c
			public const int pale_green = 2131034732;
			
			// aapt resource value: 0x7f05026d
			public const int pale_lavender = 2131034733;
			
			// aapt resource value: 0x7f05026e
			public const int pale_magenta = 2131034734;
			
			// aapt resource value: 0x7f05026f
			public const int pale_pink = 2131034735;
			
			// aapt resource value: 0x7f050270
			public const int pale_red_violet = 2131034736;
			
			// aapt resource value: 0x7f050271
			public const int pale_robin_egg_blue = 2131034737;
			
			// aapt resource value: 0x7f050272
			public const int pale_silver = 2131034738;
			
			// aapt resource value: 0x7f050273
			public const int pale_spring_bud = 2131034739;
			
			// aapt resource value: 0x7f050274
			public const int pale_taupe = 2131034740;
			
			// aapt resource value: 0x7f050275
			public const int pansy_purple = 2131034741;
			
			// aapt resource value: 0x7f050276
			public const int papaya_orange = 2131034742;
			
			// aapt resource value: 0x7f050277
			public const int papaya_whip = 2131034743;
			
			// aapt resource value: 0x7f050278
			public const int parchment = 2131034744;
			
			// aapt resource value: 0x7f050279
			public const int paris_green = 2131034745;
			
			// aapt resource value: 0x7f05027a
			public const int pastel_blue = 2131034746;
			
			// aapt resource value: 0x7f05027b
			public const int pastel_brown = 2131034747;
			
			// aapt resource value: 0x7f05027c
			public const int pastel_gray = 2131034748;
			
			// aapt resource value: 0x7f05027d
			public const int pastel_green = 2131034749;
			
			// aapt resource value: 0x7f05027e
			public const int pastel_magenta = 2131034750;
			
			// aapt resource value: 0x7f05027f
			public const int pastel_orange = 2131034751;
			
			// aapt resource value: 0x7f050280
			public const int pastel_pink = 2131034752;
			
			// aapt resource value: 0x7f050281
			public const int pastel_purple = 2131034753;
			
			// aapt resource value: 0x7f050282
			public const int pastel_red = 2131034754;
			
			// aapt resource value: 0x7f050283
			public const int pastel_violet = 2131034755;
			
			// aapt resource value: 0x7f050284
			public const int pastel_yellow = 2131034756;
			
			// aapt resource value: 0x7f050285
			public const int payne_grey = 2131034757;
			
			// aapt resource value: 0x7f050286
			public const int peach = 2131034758;
			
			// aapt resource value: 0x7f050287
			public const int peach_puff = 2131034759;
			
			// aapt resource value: 0x7f050288
			public const int peach_yellow = 2131034760;
			
			// aapt resource value: 0x7f050289
			public const int pearl = 2131034761;
			
			// aapt resource value: 0x7f05028a
			public const int pearl_aqua = 2131034762;
			
			// aapt resource value: 0x7f05028b
			public const int peridot = 2131034763;
			
			// aapt resource value: 0x7f05028c
			public const int persian_blue = 2131034764;
			
			// aapt resource value: 0x7f05028d
			public const int persian_indigo = 2131034765;
			
			// aapt resource value: 0x7f05028e
			public const int persian_orange = 2131034766;
			
			// aapt resource value: 0x7f05028f
			public const int persian_pink = 2131034767;
			
			// aapt resource value: 0x7f050290
			public const int persian_plum = 2131034768;
			
			// aapt resource value: 0x7f050291
			public const int persian_red = 2131034769;
			
			// aapt resource value: 0x7f050292
			public const int persian_rose = 2131034770;
			
			// aapt resource value: 0x7f050293
			public const int phthalo_blue = 2131034771;
			
			// aapt resource value: 0x7f050294
			public const int phthalo_green = 2131034772;
			
			// aapt resource value: 0x7f050295
			public const int pig_pink = 2131034773;
			
			// aapt resource value: 0x7f050296
			public const int piggy_pink = 2131034774;
			
			// aapt resource value: 0x7f050297
			public const int pine_green = 2131034775;
			
			// aapt resource value: 0x7f050298
			public const int pink = 2131034776;
			
			// aapt resource value: 0x7f050299
			public const int pink_bow = 2131034777;
			
			// aapt resource value: 0x7f05029a
			public const int pink_bubblegum = 2131034778;
			
			// aapt resource value: 0x7f05029b
			public const int pink_cupcake = 2131034779;
			
			// aapt resource value: 0x7f05029c
			public const int pink_daisy = 2131034780;
			
			// aapt resource value: 0x7f05029d
			public const int pink_flamingo = 2131034781;
			
			// aapt resource value: 0x7f05029e
			public const int pink_lemonade = 2131034782;
			
			// aapt resource value: 0x7f05029f
			public const int pink_pearl = 2131034783;
			
			// aapt resource value: 0x7f0502a0
			public const int pink_rose = 2131034784;
			
			// aapt resource value: 0x7f0502a1
			public const int pink_sherbet = 2131034785;
			
			// aapt resource value: 0x7f0502a2
			public const int pistachio = 2131034786;
			
			// aapt resource value: 0x7f0502a3
			public const int pistachio_green = 2131034787;
			
			// aapt resource value: 0x7f0502a4
			public const int platinum = 2131034788;
			
			// aapt resource value: 0x7f0502a5
			public const int plum = 2131034789;
			
			// aapt resource value: 0x7f0502a6
			public const int plum_pie = 2131034790;
			
			// aapt resource value: 0x7f0502a7
			public const int plum_purple = 2131034791;
			
			// aapt resource value: 0x7f0502a8
			public const int plum_velvet = 2131034792;
			
			// aapt resource value: 0x7f0502a9
			public const int portland_orange = 2131034793;
			
			// aapt resource value: 0x7f0502aa
			public const int powder_blue = 2131034794;
			
			// aapt resource value: 0x7f050008
			public const int pressed_border = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int pressed_end = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int pressed_end_multi = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int pressed_start = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int pressed_start_multi = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int pressed_text = 2131034121;
			
			// aapt resource value: 0x7f0502ab
			public const int princeton_orange = 2131034795;
			
			// aapt resource value: 0x7f0502ac
			public const int prussian_blue = 2131034796;
			
			// aapt resource value: 0x7f0502ad
			public const int psychedelic_purple = 2131034797;
			
			// aapt resource value: 0x7f0502ae
			public const int puce = 2131034798;
			
			// aapt resource value: 0x7f0502af
			public const int pumpkin = 2131034799;
			
			// aapt resource value: 0x7f0502b0
			public const int pumpkin_orange = 2131034800;
			
			// aapt resource value: 0x7f0502b1
			public const int purple = 2131034801;
			
			// aapt resource value: 0x7f0502b2
			public const int purple_amethyst = 2131034802;
			
			// aapt resource value: 0x7f0502b3
			public const int purple_daffodil = 2131034803;
			
			// aapt resource value: 0x7f0502b4
			public const int purple_dragon = 2131034804;
			
			// aapt resource value: 0x7f0502b5
			public const int purple_flower = 2131034805;
			
			// aapt resource value: 0x7f0502b6
			public const int purple_haze = 2131034806;
			
			// aapt resource value: 0x7f0502b7
			public const int purple_heart = 2131034807;
			
			// aapt resource value: 0x7f0502b8
			public const int purple_iris = 2131034808;
			
			// aapt resource value: 0x7f0502b9
			public const int purple_jam = 2131034809;
			
			// aapt resource value: 0x7f0502ba
			public const int purple_mimosa = 2131034810;
			
			// aapt resource value: 0x7f0502bb
			public const int purple_monster = 2131034811;
			
			// aapt resource value: 0x7f0502bc
			public const int purple_mountain_majesty = 2131034812;
			
			// aapt resource value: 0x7f0502bd
			public const int purple_pizzazz = 2131034813;
			
			// aapt resource value: 0x7f0502be
			public const int purple_sage_bush = 2131034814;
			
			// aapt resource value: 0x7f0502bf
			public const int purple_taupe = 2131034815;
			
			// aapt resource value: 0x7f0502c0
			public const int radical_red = 2131034816;
			
			// aapt resource value: 0x7f0502c1
			public const int raspberry = 2131034817;
			
			// aapt resource value: 0x7f0502c2
			public const int raspberry_glace = 2131034818;
			
			// aapt resource value: 0x7f0502c3
			public const int raspberry_pink = 2131034819;
			
			// aapt resource value: 0x7f0502c4
			public const int raspberry_rose = 2131034820;
			
			// aapt resource value: 0x7f0502c5
			public const int raw_sienna = 2131034821;
			
			// aapt resource value: 0x7f0502c6
			public const int razzle_dazzle_rose = 2131034822;
			
			// aapt resource value: 0x7f0502c7
			public const int razzmatazz = 2131034823;
			
			// aapt resource value: 0x7f0502c8
			public const int red = 2131034824;
			
			// aapt resource value: 0x7f0502c9
			public const int red_brown = 2131034825;
			
			// aapt resource value: 0x7f0502ca
			public const int red_dirt = 2131034826;
			
			// aapt resource value: 0x7f0502cb
			public const int red_fox = 2131034827;
			
			// aapt resource value: 0x7f0502cc
			public const int red_orange = 2131034828;
			
			// aapt resource value: 0x7f0502cd
			public const int red_violet = 2131034829;
			
			// aapt resource value: 0x7f0502ce
			public const int red_wine = 2131034830;
			
			// aapt resource value: 0x7f0502cf
			public const int rich_black = 2131034831;
			
			// aapt resource value: 0x7f0502d0
			public const int rich_carmine = 2131034832;
			
			// aapt resource value: 0x7f0502d1
			public const int rich_electric_blue = 2131034833;
			
			// aapt resource value: 0x7f0502d2
			public const int rich_lilac = 2131034834;
			
			// aapt resource value: 0x7f0502d3
			public const int rich_maroon = 2131034835;
			
			// aapt resource value: 0x7f0502d4
			public const int rifle_green = 2131034836;
			
			// aapt resource value: 0x7f0502d5
			public const int robin_egg_blue = 2131034837;
			
			// aapt resource value: 0x7f0502d6
			public const int rogue_pink = 2131034838;
			
			// aapt resource value: 0x7f0502d7
			public const int rose = 2131034839;
			
			// aapt resource value: 0x7f0502d8
			public const int rose_bonbon = 2131034840;
			
			// aapt resource value: 0x7f0502d9
			public const int rose_ebony = 2131034841;
			
			// aapt resource value: 0x7f0502da
			public const int rose_gold = 2131034842;
			
			// aapt resource value: 0x7f0502db
			public const int rose_madder = 2131034843;
			
			// aapt resource value: 0x7f0502dc
			public const int rose_pink = 2131034844;
			
			// aapt resource value: 0x7f0502dd
			public const int rose_quartz = 2131034845;
			
			// aapt resource value: 0x7f0502de
			public const int rose_taupe = 2131034846;
			
			// aapt resource value: 0x7f0502df
			public const int rose_vale = 2131034847;
			
			// aapt resource value: 0x7f0502e0
			public const int rosewood = 2131034848;
			
			// aapt resource value: 0x7f0502e1
			public const int rosso_corsa = 2131034849;
			
			// aapt resource value: 0x7f0502e2
			public const int rosy_brown = 2131034850;
			
			// aapt resource value: 0x7f0502e3
			public const int rosy_finch = 2131034851;
			
			// aapt resource value: 0x7f0502e4
			public const int royal_azure = 2131034852;
			
			// aapt resource value: 0x7f0502e5
			public const int royal_blue = 2131034853;
			
			// aapt resource value: 0x7f0502e6
			public const int royal_fuchsia = 2131034854;
			
			// aapt resource value: 0x7f0502e7
			public const int royal_purple = 2131034855;
			
			// aapt resource value: 0x7f0502e8
			public const int rubber_ducky_yellow = 2131034856;
			
			// aapt resource value: 0x7f0502e9
			public const int ruby = 2131034857;
			
			// aapt resource value: 0x7f0502ea
			public const int ruby_red = 2131034858;
			
			// aapt resource value: 0x7f0502eb
			public const int ruddy = 2131034859;
			
			// aapt resource value: 0x7f0502ec
			public const int ruddy_brown = 2131034860;
			
			// aapt resource value: 0x7f0502ed
			public const int ruddy_pink = 2131034861;
			
			// aapt resource value: 0x7f0502ee
			public const int rufous = 2131034862;
			
			// aapt resource value: 0x7f0502ef
			public const int russet = 2131034863;
			
			// aapt resource value: 0x7f0502f0
			public const int rust = 2131034864;
			
			// aapt resource value: 0x7f0502f1
			public const int sacramento_state_green = 2131034865;
			
			// aapt resource value: 0x7f0502f2
			public const int saddle_brown = 2131034866;
			
			// aapt resource value: 0x7f0502f3
			public const int safety_orange = 2131034867;
			
			// aapt resource value: 0x7f0502f4
			public const int saffron = 2131034868;
			
			// aapt resource value: 0x7f0502f5
			public const int saint_patrick_blue = 2131034869;
			
			// aapt resource value: 0x7f0502f6
			public const int salad_green = 2131034870;
			
			// aapt resource value: 0x7f0502f7
			public const int salmon = 2131034871;
			
			// aapt resource value: 0x7f0502f8
			public const int salmon_pink = 2131034872;
			
			// aapt resource value: 0x7f0502f9
			public const int sand = 2131034873;
			
			// aapt resource value: 0x7f0502fa
			public const int sandstone = 2131034874;
			
			// aapt resource value: 0x7f0502fb
			public const int sandstorm = 2131034875;
			
			// aapt resource value: 0x7f0502fc
			public const int sandy_brown = 2131034876;
			
			// aapt resource value: 0x7f0502fd
			public const int sandy_taupe = 2131034877;
			
			// aapt resource value: 0x7f0502fe
			public const int sangria = 2131034878;
			
			// aapt resource value: 0x7f0502ff
			public const int sap_green = 2131034879;
			
			// aapt resource value: 0x7f050300
			public const int sapphire = 2131034880;
			
			// aapt resource value: 0x7f050301
			public const int sapphire_blue = 2131034881;
			
			// aapt resource value: 0x7f050302
			public const int satin_sheen_gold = 2131034882;
			
			// aapt resource value: 0x7f050303
			public const int scarlet = 2131034883;
			
			// aapt resource value: 0x7f050304
			public const int school_bus_yellow = 2131034884;
			
			// aapt resource value: 0x7f050305
			public const int screamin_green = 2131034885;
			
			// aapt resource value: 0x7f050306
			public const int sea_blue = 2131034886;
			
			// aapt resource value: 0x7f050307
			public const int sea_green = 2131034887;
			
			// aapt resource value: 0x7f050308
			public const int sea_turtle_green = 2131034888;
			
			// aapt resource value: 0x7f050309
			public const int seal_brown = 2131034889;
			
			// aapt resource value: 0x7f05030a
			public const int seashell = 2131034890;
			
			// aapt resource value: 0x7f05030b
			public const int seaweed_green = 2131034891;
			
			// aapt resource value: 0x7f05030c
			public const int sedona = 2131034892;
			
			// aapt resource value: 0x7f05030d
			public const int selective_yellow = 2131034893;
			
			// aapt resource value: 0x7f05030e
			public const int sepia = 2131034894;
			
			// aapt resource value: 0x7f05030f
			public const int shadow = 2131034895;
			
			// aapt resource value: 0x7f050310
			public const int shamrock = 2131034896;
			
			// aapt resource value: 0x7f050311
			public const int shamrock_green = 2131034897;
			
			// aapt resource value: 0x7f050312
			public const int shocking_orange = 2131034898;
			
			// aapt resource value: 0x7f050313
			public const int shocking_pink = 2131034899;
			
			// aapt resource value: 0x7f050314
			public const int sienna = 2131034900;
			
			// aapt resource value: 0x7f050315
			public const int silk_blue = 2131034901;
			
			// aapt resource value: 0x7f050316
			public const int silver = 2131034902;
			
			// aapt resource value: 0x7f050317
			public const int sinopia = 2131034903;
			
			// aapt resource value: 0x7f050318
			public const int skobeloff = 2131034904;
			
			// aapt resource value: 0x7f050319
			public const int sky_blue = 2131034905;
			
			// aapt resource value: 0x7f05031a
			public const int sky_magenta = 2131034906;
			
			// aapt resource value: 0x7f05031b
			public const int slate_blue = 2131034907;
			
			// aapt resource value: 0x7f05031c
			public const int slate_gray = 2131034908;
			
			// aapt resource value: 0x7f05031d
			public const int slime_green = 2131034909;
			
			// aapt resource value: 0x7f05031e
			public const int smokey_gray = 2131034910;
			
			// aapt resource value: 0x7f05031f
			public const int smokey_topaz = 2131034911;
			
			// aapt resource value: 0x7f050320
			public const int smoky_black = 2131034912;
			
			// aapt resource value: 0x7f050321
			public const int snow = 2131034913;
			
			// aapt resource value: 0x7f050322
			public const int spiro_disco_ball = 2131034914;
			
			// aapt resource value: 0x7f050323
			public const int spring_bud = 2131034915;
			
			// aapt resource value: 0x7f050324
			public const int spring_green = 2131034916;
			
			// aapt resource value: 0x7f050325
			public const int steel_blue = 2131034917;
			
			// aapt resource value: 0x7f050326
			public const int stil_de_grain_yellow = 2131034918;
			
			// aapt resource value: 0x7f050327
			public const int stoplight_go_green = 2131034919;
			
			// aapt resource value: 0x7f050328
			public const int straw = 2131034920;
			
			// aapt resource value: 0x7f050329
			public const int sun_yellow = 2131034921;
			
			// aapt resource value: 0x7f05032a
			public const int sunglow = 2131034922;
			
			// aapt resource value: 0x7f05032b
			public const int sunrise_orange = 2131034923;
			
			// aapt resource value: 0x7f05032c
			public const int sunset = 2131034924;
			
			// aapt resource value: 0x7f05032d
			public const int sunset_orange = 2131034925;
			
			// aapt resource value: 0x7f05032e
			public const int tan = 2131034926;
			
			// aapt resource value: 0x7f05032f
			public const int tan_brown = 2131034927;
			
			// aapt resource value: 0x7f050330
			public const int tangelo = 2131034928;
			
			// aapt resource value: 0x7f050331
			public const int tangerine = 2131034929;
			
			// aapt resource value: 0x7f050332
			public const int tangerine_yellow = 2131034930;
			
			// aapt resource value: 0x7f050333
			public const int taupe = 2131034931;
			
			// aapt resource value: 0x7f050334
			public const int taupe_gray = 2131034932;
			
			// aapt resource value: 0x7f050335
			public const int tawny = 2131034933;
			
			// aapt resource value: 0x7f050336
			public const int tea_green = 2131034934;
			
			// aapt resource value: 0x7f050337
			public const int tea_rose = 2131034935;
			
			// aapt resource value: 0x7f050338
			public const int teal = 2131034936;
			
			// aapt resource value: 0x7f050339
			public const int teal_blue = 2131034937;
			
			// aapt resource value: 0x7f05033a
			public const int teal_green = 2131034938;
			
			// aapt resource value: 0x7f05033b
			public const int terra_cotta = 2131034939;
			
			// aapt resource value: 0x7f05033c
			public const int thistle = 2131034940;
			
			// aapt resource value: 0x7f05033d
			public const int thulian_pink = 2131034941;
			
			// aapt resource value: 0x7f05033e
			public const int tickle_me_pink = 2131034942;
			
			// aapt resource value: 0x7f05033f
			public const int tiffany_blue = 2131034943;
			
			// aapt resource value: 0x7f050340
			public const int tiger_eye = 2131034944;
			
			// aapt resource value: 0x7f050341
			public const int tiger_orange = 2131034945;
			
			// aapt resource value: 0x7f050342
			public const int timberwolf = 2131034946;
			
			// aapt resource value: 0x7f050343
			public const int titanium_yellow = 2131034947;
			
			// aapt resource value: 0x7f050344
			public const int tomato = 2131034948;
			
			// aapt resource value: 0x7f050345
			public const int toolbox = 2131034949;
			
			// aapt resource value: 0x7f050346
			public const int topaz = 2131034950;
			
			// aapt resource value: 0x7f050347
			public const int tractor_red = 2131034951;
			
			// aapt resource value: 0x7f050390
			public const int transparent_black_hex_1 = 2131035024;
			
			// aapt resource value: 0x7f050399
			public const int transparent_black_hex_10 = 2131035033;
			
			// aapt resource value: 0x7f05039a
			public const int transparent_black_hex_11 = 2131035034;
			
			// aapt resource value: 0x7f05039b
			public const int transparent_black_hex_12 = 2131035035;
			
			// aapt resource value: 0x7f05039c
			public const int transparent_black_hex_13 = 2131035036;
			
			// aapt resource value: 0x7f05039d
			public const int transparent_black_hex_14 = 2131035037;
			
			// aapt resource value: 0x7f05039e
			public const int transparent_black_hex_15 = 2131035038;
			
			// aapt resource value: 0x7f050391
			public const int transparent_black_hex_2 = 2131035025;
			
			// aapt resource value: 0x7f050392
			public const int transparent_black_hex_3 = 2131035026;
			
			// aapt resource value: 0x7f050393
			public const int transparent_black_hex_4 = 2131035027;
			
			// aapt resource value: 0x7f050394
			public const int transparent_black_hex_5 = 2131035028;
			
			// aapt resource value: 0x7f050395
			public const int transparent_black_hex_6 = 2131035029;
			
			// aapt resource value: 0x7f050396
			public const int transparent_black_hex_7 = 2131035030;
			
			// aapt resource value: 0x7f050397
			public const int transparent_black_hex_8 = 2131035031;
			
			// aapt resource value: 0x7f050398
			public const int transparent_black_hex_9 = 2131035032;
			
			// aapt resource value: 0x7f0503a0
			public const int transparent_black_percent_10 = 2131035040;
			
			// aapt resource value: 0x7f0503a1
			public const int transparent_black_percent_15 = 2131035041;
			
			// aapt resource value: 0x7f0503a2
			public const int transparent_black_percent_20 = 2131035042;
			
			// aapt resource value: 0x7f0503a3
			public const int transparent_black_percent_25 = 2131035043;
			
			// aapt resource value: 0x7f0503a4
			public const int transparent_black_percent_30 = 2131035044;
			
			// aapt resource value: 0x7f0503a5
			public const int transparent_black_percent_35 = 2131035045;
			
			// aapt resource value: 0x7f0503a6
			public const int transparent_black_percent_40 = 2131035046;
			
			// aapt resource value: 0x7f0503a7
			public const int transparent_black_percent_45 = 2131035047;
			
			// aapt resource value: 0x7f05039f
			public const int transparent_black_percent_5 = 2131035039;
			
			// aapt resource value: 0x7f0503a8
			public const int transparent_black_percent_50 = 2131035048;
			
			// aapt resource value: 0x7f0503a9
			public const int transparent_black_percent_55 = 2131035049;
			
			// aapt resource value: 0x7f0503aa
			public const int transparent_black_percent_60 = 2131035050;
			
			// aapt resource value: 0x7f0503ab
			public const int transparent_black_percent_65 = 2131035051;
			
			// aapt resource value: 0x7f0503ac
			public const int transparent_black_percent_70 = 2131035052;
			
			// aapt resource value: 0x7f0503ad
			public const int transparent_black_percent_75 = 2131035053;
			
			// aapt resource value: 0x7f0503ae
			public const int transparent_black_percent_80 = 2131035054;
			
			// aapt resource value: 0x7f0503af
			public const int transparent_black_percent_85 = 2131035055;
			
			// aapt resource value: 0x7f0503b0
			public const int transparent_black_percent_90 = 2131035056;
			
			// aapt resource value: 0x7f0503b1
			public const int transparent_black_percent_95 = 2131035057;
			
			// aapt resource value: 0x7f0503b2
			public const int transparent_white_hex_1 = 2131035058;
			
			// aapt resource value: 0x7f0503bb
			public const int transparent_white_hex_10 = 2131035067;
			
			// aapt resource value: 0x7f0503bc
			public const int transparent_white_hex_11 = 2131035068;
			
			// aapt resource value: 0x7f0503bd
			public const int transparent_white_hex_12 = 2131035069;
			
			// aapt resource value: 0x7f0503be
			public const int transparent_white_hex_13 = 2131035070;
			
			// aapt resource value: 0x7f0503bf
			public const int transparent_white_hex_14 = 2131035071;
			
			// aapt resource value: 0x7f0503c0
			public const int transparent_white_hex_15 = 2131035072;
			
			// aapt resource value: 0x7f0503b3
			public const int transparent_white_hex_2 = 2131035059;
			
			// aapt resource value: 0x7f0503b4
			public const int transparent_white_hex_3 = 2131035060;
			
			// aapt resource value: 0x7f0503b5
			public const int transparent_white_hex_4 = 2131035061;
			
			// aapt resource value: 0x7f0503b6
			public const int transparent_white_hex_5 = 2131035062;
			
			// aapt resource value: 0x7f0503b7
			public const int transparent_white_hex_6 = 2131035063;
			
			// aapt resource value: 0x7f0503b8
			public const int transparent_white_hex_7 = 2131035064;
			
			// aapt resource value: 0x7f0503b9
			public const int transparent_white_hex_8 = 2131035065;
			
			// aapt resource value: 0x7f0503ba
			public const int transparent_white_hex_9 = 2131035066;
			
			// aapt resource value: 0x7f0503c2
			public const int transparent_white_percent_10 = 2131035074;
			
			// aapt resource value: 0x7f0503c3
			public const int transparent_white_percent_15 = 2131035075;
			
			// aapt resource value: 0x7f0503c4
			public const int transparent_white_percent_20 = 2131035076;
			
			// aapt resource value: 0x7f0503c5
			public const int transparent_white_percent_25 = 2131035077;
			
			// aapt resource value: 0x7f0503c6
			public const int transparent_white_percent_30 = 2131035078;
			
			// aapt resource value: 0x7f0503c7
			public const int transparent_white_percent_35 = 2131035079;
			
			// aapt resource value: 0x7f0503c8
			public const int transparent_white_percent_40 = 2131035080;
			
			// aapt resource value: 0x7f0503c9
			public const int transparent_white_percent_45 = 2131035081;
			
			// aapt resource value: 0x7f0503c1
			public const int transparent_white_percent_5 = 2131035073;
			
			// aapt resource value: 0x7f0503ca
			public const int transparent_white_percent_50 = 2131035082;
			
			// aapt resource value: 0x7f0503cb
			public const int transparent_white_percent_55 = 2131035083;
			
			// aapt resource value: 0x7f0503cc
			public const int transparent_white_percent_60 = 2131035084;
			
			// aapt resource value: 0x7f0503cd
			public const int transparent_white_percent_65 = 2131035085;
			
			// aapt resource value: 0x7f0503ce
			public const int transparent_white_percent_70 = 2131035086;
			
			// aapt resource value: 0x7f0503cf
			public const int transparent_white_percent_75 = 2131035087;
			
			// aapt resource value: 0x7f0503d0
			public const int transparent_white_percent_80 = 2131035088;
			
			// aapt resource value: 0x7f0503d1
			public const int transparent_white_percent_85 = 2131035089;
			
			// aapt resource value: 0x7f0503d2
			public const int transparent_white_percent_90 = 2131035090;
			
			// aapt resource value: 0x7f0503d3
			public const int transparent_white_percent_95 = 2131035091;
			
			// aapt resource value: 0x7f050348
			public const int tron_blue = 2131034952;
			
			// aapt resource value: 0x7f050349
			public const int tropical_rain_forest = 2131034953;
			
			// aapt resource value: 0x7f05034a
			public const int true_blue = 2131034954;
			
			// aapt resource value: 0x7f05034b
			public const int tufts_blue = 2131034955;
			
			// aapt resource value: 0x7f05034c
			public const int tulip_pink = 2131034956;
			
			// aapt resource value: 0x7f05034d
			public const int tumbleweed = 2131034957;
			
			// aapt resource value: 0x7f05034e
			public const int turkish_rose = 2131034958;
			
			// aapt resource value: 0x7f05034f
			public const int turquoise = 2131034959;
			
			// aapt resource value: 0x7f050350
			public const int turquoise_blue = 2131034960;
			
			// aapt resource value: 0x7f050351
			public const int turquoise_green = 2131034961;
			
			// aapt resource value: 0x7f050352
			public const int tuscan_red = 2131034962;
			
			// aapt resource value: 0x7f050353
			public const int twilight_lavender = 2131034963;
			
			// aapt resource value: 0x7f050354
			public const int tyrian_purple = 2131034964;
			
			// aapt resource value: 0x7f050355
			public const int ua_blue = 2131034965;
			
			// aapt resource value: 0x7f050356
			public const int ua_red = 2131034966;
			
			// aapt resource value: 0x7f050357
			public const int ube = 2131034967;
			
			// aapt resource value: 0x7f050358
			public const int ucla_blue = 2131034968;
			
			// aapt resource value: 0x7f050359
			public const int ucla_gold = 2131034969;
			
			// aapt resource value: 0x7f05035a
			public const int ufo_green = 2131034970;
			
			// aapt resource value: 0x7f05035b
			public const int ultra_pink = 2131034971;
			
			// aapt resource value: 0x7f05035c
			public const int ultramarine = 2131034972;
			
			// aapt resource value: 0x7f05035d
			public const int ultramarine_blue = 2131034973;
			
			// aapt resource value: 0x7f05035e
			public const int umber = 2131034974;
			
			// aapt resource value: 0x7f05035f
			public const int united_nations_blue = 2131034975;
			
			// aapt resource value: 0x7f050360
			public const int university_of_california_gold = 2131034976;
			
			// aapt resource value: 0x7f050361
			public const int unmellow_yellow = 2131034977;
			
			// aapt resource value: 0x7f050362
			public const int up_forest_green = 2131034978;
			
			// aapt resource value: 0x7f050363
			public const int up_maroon = 2131034979;
			
			// aapt resource value: 0x7f050364
			public const int upsdell_red = 2131034980;
			
			// aapt resource value: 0x7f050365
			public const int urobilin = 2131034981;
			
			// aapt resource value: 0x7f050366
			public const int utah_crimson = 2131034982;
			
			// aapt resource value: 0x7f050367
			public const int valentine_red = 2131034983;
			
			// aapt resource value: 0x7f050368
			public const int vampire_gray = 2131034984;
			
			// aapt resource value: 0x7f050369
			public const int vanilla = 2131034985;
			
			// aapt resource value: 0x7f05036a
			public const int vegas_gold = 2131034986;
			
			// aapt resource value: 0x7f05036b
			public const int velvet_maroon = 2131034987;
			
			// aapt resource value: 0x7f05036c
			public const int venetian_red = 2131034988;
			
			// aapt resource value: 0x7f05036d
			public const int venom_green = 2131034989;
			
			// aapt resource value: 0x7f05036e
			public const int verdigris = 2131034990;
			
			// aapt resource value: 0x7f05036f
			public const int veronica = 2131034991;
			
			// aapt resource value: 0x7f050370
			public const int viola_purple = 2131034992;
			
			// aapt resource value: 0x7f050371
			public const int violet = 2131034993;
			
			// aapt resource value: 0x7f050372
			public const int violet_blue = 2131034994;
			
			// aapt resource value: 0x7f050373
			public const int violet_red = 2131034995;
			
			// aapt resource value: 0x7f050374
			public const int viridian = 2131034996;
			
			// aapt resource value: 0x7f050375
			public const int vivid_auburn = 2131034997;
			
			// aapt resource value: 0x7f050376
			public const int vivid_burgundy = 2131034998;
			
			// aapt resource value: 0x7f050377
			public const int vivid_cerise = 2131034999;
			
			// aapt resource value: 0x7f050378
			public const int vivid_tangerine = 2131035000;
			
			// aapt resource value: 0x7f050379
			public const int vivid_violet = 2131035001;
			
			// aapt resource value: 0x7f05037a
			public const int warm_black = 2131035002;
			
			// aapt resource value: 0x7f05037b
			public const int water = 2131035003;
			
			// aapt resource value: 0x7f05037c
			public const int watermelon_pink = 2131035004;
			
			// aapt resource value: 0x7f05037d
			public const int wenge = 2131035005;
			
			// aapt resource value: 0x7f05037e
			public const int wheat = 2131035006;
			
			// aapt resource value: 0x7f05037f
			public const int white = 2131035007;
			
			// aapt resource value: 0x7f050380
			public const int white_smoke = 2131035008;
			
			// aapt resource value: 0x7f050381
			public const int wild_blue_yonder = 2131035009;
			
			// aapt resource value: 0x7f050382
			public const int wild_strawberry = 2131035010;
			
			// aapt resource value: 0x7f050383
			public const int wild_watermelon = 2131035011;
			
			// aapt resource value: 0x7f050384
			public const int wine = 2131035012;
			
			// aapt resource value: 0x7f050385
			public const int wiseria_purple = 2131035013;
			
			// aapt resource value: 0x7f050386
			public const int wisteria = 2131035014;
			
			// aapt resource value: 0x7f050387
			public const int wood = 2131035015;
			
			// aapt resource value: 0x7f050388
			public const int xanadu = 2131035016;
			
			// aapt resource value: 0x7f050389
			public const int yale_blue = 2131035017;
			
			// aapt resource value: 0x7f05038a
			public const int yellow = 2131035018;
			
			// aapt resource value: 0x7f05038b
			public const int yellow_green = 2131035019;
			
			// aapt resource value: 0x7f05038c
			public const int yellow_orange = 2131035020;
			
			// aapt resource value: 0x7f05038d
			public const int zaffre = 2131035021;
			
			// aapt resource value: 0x7f05038e
			public const int zinnwaldite_brown = 2131035022;
			
			// aapt resource value: 0x7f05038f
			public const int zombie_green = 2131035023;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_save = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int ViewDescricaoProdutoPedido = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int ViewIDProdutoPedido = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int ViewPrecoProdutoPedido = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int ViewQtdeProdutoPedido = 2131099651;
			
			// aapt resource value: 0x7f060021
			public const int btnSalvar = 2131099681;
			
			// aapt resource value: 0x7f060011
			public const int lblData = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int lblHora = 2131099667;
			
			// aapt resource value: 0x7f06000e
			public const int lblNome = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int lblNumOrdem = 2131099659;
			
			// aapt resource value: 0x7f060015
			public const int lblObservacaoGeral = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int lblPreco = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int lblProduto = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int lblQtde = 2131099673;
			
			// aapt resource value: 0x7f060008
			public const int lblTitulo = 2131099656;
			
			// aapt resource value: 0x7f06001d
			public const int lblTotal = 2131099677;
			
			// aapt resource value: 0x7f06001b
			public const int lstItemPedido = 2131099675;
			
			// aapt resource value: 0x7f060020
			public const int pnlBotao = 2131099680;
			
			// aapt resource value: 0x7f060006
			public const int pnlDadosPedido = 2131099654;
			
			// aapt resource value: 0x7f060010
			public const int pnlDataHora = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int pnlNome = 2131099661;
			
			// aapt resource value: 0x7f06000a
			public const int pnlNumOrdem = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int pnlPedido = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int pnlPrincipal = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int pnlRoot = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int pnlTituloItens = 2131099671;
			
			// aapt resource value: 0x7f060007
			public const int pnlTituloPedido = 2131099655;
			
			// aapt resource value: 0x7f06001c
			public const int pnlTotal = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int signatureView = 2131099679;
			
			// aapt resource value: 0x7f060012
			public const int txtData = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int txtHora = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int txtNome = 2131099663;
			
			// aapt resource value: 0x7f06000c
			public const int txtNumOrdem = 2131099660;
			
			// aapt resource value: 0x7f060016
			public const int txtObsGeral = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int txtTotal = 2131099678;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListItemPedido = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
